### ISSUE TITLE
[Sneakers theme] theme does not work under Edge/Internet explorer

### ISSUE THREAD

**Issue by hirisov** [oc-shopaholic/oc-shopaholic-plugin#249]
The sneakers theme officially supports Edge, but does not work at all in Edge, no page loads on the frontend. The backend works in Edge, so it's a theme related problem.

**Comment by lautsevich** [comment]
Hi, could you please provide more information? Which Edge version do you use? Which OS version?

I confirm that the bug on Win10/Edge18.

Buy the way, it is a big surprise. The theme has been working before.

We'll investigate it and provide fix asap.

**Comment by lautsevich** [comment]
Hi, could you please provide more information? Which Edge version do you use? Which OS version?

I confirm that the bug on Win10/Edge18.

Buy the way, it is a big surprise. The theme has been working before.

We'll investigate it and provide fix asap.

**Comment by lautsevich** [comment]
@hirisov, could you please try out this solution? https://answers.microsoft.com/en-us/edge/forum/all/edge-cant-load-any-web-pages-after-win-10-october/8e985039-1bc0-4586-93ce-1be0af14733a

**Comment by lautsevich** [comment]
@hirisov, we've found the reason and will fix it in the next release.

This selector in `awecssome` NPM dependency crashes Edge:

```CSS
.subgrid.full-width {
  display: grid;
  grid-template-columns: inherit; /* This rule crashes Edge! */
}
```
Quickfix is as follows. Override this rule in your custom CSS somewhere below the import of the `awecssome` dependency in `common.css` file:

```CSS
.subgrid.full-width {
  grid-template-columns: var(--grid-template-columns);
}
```
I'll move this issue to the private repository of the Sneakers theme.
